defaults: &defaults
  twitter:
    api:
      token_path: /oauth2/token
      key: <%= ENV['TWITSEARCH_TWITTER_CONSUMER_KEY'] %>
      secret: <%= ENV['TWITSEARCH_TWITTER_CONSUMER_SECRET'] %>
      search_path: /1.1/search/tweets.json
      trends_path: /1.1/trends/place.json
      locations_path: /1.1/trends/available.json
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

